spring:
  application:
    name: currency-conversion


  cloud:
    config:
      enabled: false
Server:
  port: 8100
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka